### ISSUE TITLE
Честный sync

### ISSUE THREAD

**Issue by lgg** [xmoonlight/includeHTML#1]
```
includeHTML('header.html', document.getElementById('mainmenu'), function(){
        includeHTML('menu.html', document.getElementById('pagemenu'));
      });
```

Это callback hell, а не sync ;)

Может promises? или массивом/объектами передавать нужное и оно там уже само внутри себя callback hell устроит?

например:

```
includeHTML.sync([
     ['header.html', 'mainmenu'], ['main.html', 'main'], ['menu.html', 'pagemenu']
]);
```

**Comment by xmoonlight** [comment]
Согласен. Если реализуете - я добавлю.

**Comment by lgg** [comment]
@xmoonlight ок, допилю как-нибудь.

**Comment by lgg** [comment]
@xmoonlight оставили бы этот и #2 открытыми :/

**Comment by lgg** [comment]
Решил не заморачиваться с promise и остальным и сделать просто генератор callback hell'a внутри.
