### ISSUE TITLE
Загрузка блока по якорю

### ISSUE THREAD

**Issue by lgg** [xmoonlight/includeHTML#3]
А если у нас будет таких секций штук 12-15 и мы перейдем на страницу по якорю `#section13`
то не факт, что к этому моменту секция прогрузится. 

Мб добавить опцию какой-нибудь проверки, чтобы проверяло передан ли якорь, который соответствует подгружаемой секции.

**Comment by xmoonlight** [comment]
На текущий момент: 
Активацию ссылки на секцию лучше делать через callback, чтобы быть уверенным на 100%, что секция к моменту клика будет уже загружена полностью.
Иначе - нужно писать сразу полноценный роутинг со всеми событиями и ответчиками для полного контроля загрузки блоков.
