### ISSUE TITLE
Anchor (#) navigation question [Resolved!]

### ISSUE THREAD

**Issue by lgg** [xmoonlight/includeHTML#4]
Еще не совсем понятен такой момент:
опять страница 10-15 блоков, переходим на 12 блок, а несколько предыдущих еще не подгружены, когда подгрузятся, то на странице собьется скролл. Как быть в данной ситуации?

**Comment by xmoonlight** [comment]
Это частный случай, когда необходимо переходить (проматывать) страницу к якорю.
Можно воспользоваться асинхронной загрузкой для ожидания загрузки всех (или необходимых: тех, что находятся исключительно выше нужного) блоков, затем - определить позицию на странице и выполнить искусственный скролл на этот блок через JS.
