### ISSUE TITLE
User bug - FIXED!

### ISSUE THREAD

**Issue by lgg** [xmoonlight/includeHTML#6]
Demo: https://fedos.top/demo/index.html

**Comment by lgg** [comment]
Я хотел закрыть #1 и #2, но у меня никак не хочет работать. ЧЯДНТ?

**Comment by xmoonlight** [comment]
У Вас объект test ещё не создан. 
Дождитесь полной загрузки DOM.
Учите: https://learn.javascript.ru/onload-ondomcontentloaded

**Comment by lgg** [comment]
@xmoonlight https://fedos.top/demo/index.html https://fedos.top/demo/test2.html

В документации ничего об этом не написано, так что не совсем очевидно, что нужно оборачивать в domloaded.

**Comment by xmoonlight** [comment]
@lgg, это общий случай, не нуждающийся в отдельном дополнительном документировании. 
Чтобы правильно применять любые JS-функции к объектам, достаточно понимать загрузку веб-страницы браузером.
Еще раз говорю: учите: https://learn.javascript.ru/onload-ondomcontentloaded

**Comment by lgg** [comment]
@xmoonlight я убрал там вообще js includeHTML, остались только теги, которые согласно документации должны подтягиваться автоматически.

А по поводу доп документирования - многие js плагины сами внутри себя вешают проверку на наличие элементы/прогрузку DOM'a.

**Comment by xmoonlight** [comment]
@lgg по-внимательнее пишите код: Вы там ошиблись: 

> include scr=

вместо src=

А по поводу доп документирования - если Вы загружаете JS-функцией, Вы сами должны контролировать процесс. А по многим js-плагинам: пример - в студию.

**Comment by lgg** [comment]
@xmoonlight посыпаю голову пеплом. 

К слову, у Вас в коде был биндинг на `window.onload` событие, поменял на addEventListener, помогло.

**Comment by lgg** [comment]
@xmoonlight вроде fotorama и fullpage,js так делают.

**Comment by xmoonlight** [comment]
> К слову, у Вас в коде был биндинг на window.onload событие, поменял на addEventListener, помогло.

Возможно, т.к. я не во всех тестил. 
А Вы в каком браузере тестили и обнаружили эту ошибку?

**Comment by lgg** [comment]
@xmoonlight Chrome. 

Вот пример: https://fedos.top/demo/
Там сейчас старая версия includeHTML.

**Comment by xmoonlight** [comment]
> include scr=

**Comment by lgg** [comment]
@xmoonlight da fuck >< 
Поправил, а потом снова на старый пример откатился. 

https://fedos.top/demo/ 
теперь `src=`
но onload перезаписывается.

**Comment by xmoonlight** [comment]
@lgg, ну если подменить=переопределить функцию - конечно не сработает.
так можно с любой сделать (+и событие так же переопределить)...
это не показатель.

**Comment by xmoonlight** [comment]
режим Append для window.onload:

```
var fn = window.onload;
window.onload = function() { 
   fn && fn() //если задана - исполняем.
   /*
    затем уже - всякие алерты!
   */
}
```

**Comment by lgg** [comment]
@xmoonlight всё равно использовать биндинг функций через `on` не есть гуд. Лучше, через `addEventListener`

**Comment by xmoonlight** [comment]
@lgg ок, Аргументируйте.

**Comment by lgg** [comment]
@xmoonlight https://learn.javascript.ru/introduction-browser-events#недостаток-назначения-через-свойство

**Comment by xmoonlight** [comment]
@lgg в ответ я могу сказать: чтобы добиться кросс-браузерности с addEventListener - нужно около 60 строк кода и тучу условий внутри: http://javascript.info/tutorial/onload-ondomcontentloaded
А прописать window.onload в режиме Append: всего +2 строки (их надо дописать в имеющийся код!).
Поэтому этот вариант - предпочтительнее для уменьшения размера и кол-ва логических операций, что скажется на производительности и он будет работать быстрее.

**Comment by lgg** [comment]
@xmoonlight addEventListener работает с IE9 же. Зачем кросс-браузерность на более старый версии?

**Comment by lgg** [comment]
@xmoonlight кстати, вот почему у меня был scr вместо src

![image](https://cloud.githubusercontent.com/assets/12018713/18635559/2022be00-7e8e-11e6-9e0a-ace5900daff9.png)

**Comment by xmoonlight** [comment]
> кстати, вот почему у меня был scr вместо src

Блин, правил же предыдущую версию, а потом снова затянул с ошибкой с локальной папки.....
Поправил!

**Comment by xmoonlight** [comment]
> addEventListener работает с IE9 же. Зачем кросс-браузерность на более старый версии?

Здесь речь даже не сколько про IE9, сколько про другие браузеры для мобил, SmartTV и телеприставок различных типов и направлений.
Т.е. я понял, что есть желание заменить на вот это:

> All browsers except IE<9 support it.
> `document.addEventListener( "DOMContentLoaded", ready, false )`

Тогда надо как-то совместить, если вдруг addEventListener - окажется недоступен. 
Первым делом, разумеется, его проверяем.
http://caniuse.com/#feat=domcontentloaded

**Comment by lgg** [comment]
@xmoonlight так вроде в том же самом caniuse написано, что все мобилки поддерживают его. 

Тут скорее даже проблема не с самим плагином(что внутри него биндинг будет через window.onload), а с теми пользователями, которые будут сами что-то делать через window.onload и тогда вот они уже перекроют биндинг внутри плагина.

**Comment by xmoonlight** [comment]
Если они заменят после (как в твоём примере) - то да, затрут они.
Если до этого - то я прописал append-переброску и код плагина выполнит их код, а потом уже - свой и ничего не пропадёт.

Т.е. тот, кто использует window.onload должен:
1. или юзать его однократно в коде страницы в любом месте (в плагине includeHTML уже 1 раз есть)
2. или ставить выше загрузки кода плагина includeHTML (чтобы плагин делал прокидку событий)
3. или не забывать делать Append в 2 строки, чтобы не затирать предыдущую инициализацию

По логике: этот плагин - первый JS-код, который должен появиться в момент вёрстки, так что если затрут - сразу заметят, что это их ошибка и поправят уже свой код.
